# Site settings
title: ACM UTSA
email: team@acmutsa.org
author: Zaquariah Holland
description: >-
  "The Association for Computing Machinery at UTSA is dedicated to giving members and students the
   opportunity to gain experience, network, socialize, learn, and grow outside of the classroom in
   all fields of technology and computing."
baseurl: /acmutsa.github.io
url: https://acmutsa.github.io

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: UTSA-ACM
twitter_username: acmutsa

# plugins
plugins: [jekyll-paginate]
paginate: 3